namespace GoodTimeStudio.MyPhone.OBEX.Map;

public enum MasAppParamTagId : byte
{
    MaxListCount = 0x01,
    ListStartOffset,
    FilterMessageType,
    FilterPeriodBegin,
    EndFilterPeriodEnd,
    FilterReadStatus,
    FilterRecipient,
    FilterOriginator,
    FilterPriority,
    Attachment,
    Transparent,
    Retry,
    NewMessage,
    NotificationStatus,
    MasInstanceId,
    ParameterMask,
    FolderListingSize,
    ListingSize,
    SubjectLength,
    Charset,
    FractionRequest,
    FractionDeliver,
    StatusIndicator,
    StatusValue,
    MseTime,
    DatabaseIdentifier,
    ConversationListingVersionCounter,
    PresenceAvailability,
    PresenceText,
    LastActivity,
    FilterLastActivityBegin,
    FilterLastActivityEnd,
    ChatState,
    ConversationId,
    FolderVersionCounter,
    FilterMessageHandle,
    NotificationFilterMask,
    ConvParameterMask,
    OwnerUci,
    ExtendedData,
    MapSupportedFeatures,
    MessageHandle,
    ModifyText,
}
